#!/bin/bash

#mogrify -scale 50% ../Graphics/@1x/Images/*.png
#mogrify -scale 50% ../Graphics/@1x/Images/uiview/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/deck/cannons/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/deck/extras/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/deck/helms/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/deck/railings/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/deck/dutchman/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/ships/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/gadgets/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/playfield/voodoo/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/common/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/entrance/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/etherealsHauntVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/merchantVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/scumPrisonVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/shipyardVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/tavernVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/villainsDenVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/cove2/parlorVenue/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/tavern/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/title/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/title/buttons/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/handbook/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/splash/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/cannons/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/gadgets/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/ships/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/voodoo/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/cabin/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/gadget-shop/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/shipyard/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/swindlers-alley/voodoo-shop/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/achievements/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/gameover/*.png
mogrify -scale 50% ../Graphics/@1x/Atlases/help/*.png
